name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          package-name: >
            pkg_commons
            pkg_reasoning
            pkg_audio_input
            pkg_launch
          vcs-repo-file-url: ''
